/* Scaffold-owned UI kit — import from "./_ui". Do NOT edit or overwrite this file. */
import type { CSSProperties, ReactNode } from "react";

const figureStyle: CSSProperties = {
  position: "relative",
  display: "block",
  margin: 0,
  overflow: "hidden",
};
const imgStyleBase: CSSProperties = {
  display: "block",
  width: "100%",
  height: "100%",
  objectFit: "cover",
};
const badgeStyle: CSSProperties = {
  position: "absolute",
  left: "0.75rem",
  bottom: "0.75rem",
  zIndex: 2,
  display: "inline-flex",
  alignItems: "center",
  gap: "0.4rem",
  padding: "0.32rem 0.72rem",
  borderRadius: "999px",
  fontSize: "0.68rem",
  fontWeight: 600,
  letterSpacing: "0.04em",
  lineHeight: 1,
  whiteSpace: "nowrap",
  color: "rgba(255,255,255,0.94)",
  background: "rgba(17,20,24,0.55)",
  backdropFilter: "blur(6px)",
  WebkitBackdropFilter: "blur(6px)",
  border: "1px solid rgba(255,255,255,0.18)",
  pointerEvents: "none",
};

/** Wrapper for every AI-generated image: renders the image plus the mandatory
 *  "generated by AI" badge. Always use this instead of a bare <img> for generated
 *  imagery — never remove or cover the badge. Size/crop via className/style on the
 *  wrapper (it is the positioned box; the image fills it with object-fit: cover). */
export function AiImage({
  src,
  alt,
  label = "Ilustrační náhled — vygenerováno AI",
  className,
  style,
  imgStyle,
  children,
}: {
  src: string;
  alt: string;
  label?: string;
  className?: string;
  style?: CSSProperties;
  imgStyle?: CSSProperties;
  children?: ReactNode;
}) {
  return (
    <figure className={className} style={{ ...figureStyle, ...style }}>
      <img src={src} alt={alt} style={{ ...imgStyleBase, ...imgStyle }} />
      {children}
      <figcaption style={badgeStyle}>
        <span aria-hidden="true" style={{ opacity: 0.75 }}>✦</span>
        {label}
      </figcaption>
    </figure>
  );
}
